Feat:/#23 Applicant info update
KDT3-final-project-team2/backend pull request #28
Opened 2023-03-23 10:08 UTC by 724thomas

## Why need this change? 
- 개인회원 정보 수정 API입니다.

## Changes ✏️
Added files:
- ApplicantController
- ApplicationInfoUpdateRequest (DTO)
- ApplicationInfoUpdateResponse (DTO)
- Applicant (Entity)
- ApplicationInfoUpdateRepository
- ApplicationInfoUpdateService
- ApplicationInfoUpdateServiceImpl

## Test checklist✅ (optional)
#23

2023-03-23 10:30 UTC, 724thomas commented
토큰에서 아이디 가져오는 기능 나오면, 추가 예정입니다!

2023-03-23 12:35 UTC, HongGuma requested changes

2023-03-23 12:35 UTC, HongGuma commented on src/main/java/com/project/finalproject/applicant/dto/request/ApplicantInfoUpdateRequest.java
> +@Data
Data 어노테이션에는 너무 많이 들어가있어서 getter나 setter같은 필요한것만 꺼내 쓰는게 좋습니다..! (미니때 멘토링 받음)

2023-03-23 21:56 UTC, 724thomas commented
로컬파일 노트북에 있어서 월요일날 학원에서 마무리 하겠습니다~

2023-03-23 21:56 UTC, 724thomas commented on src/main/java/com/project/finalproject/applicant/dto/request/ApplicantInfoUpdateRequest.java
> +@Data
넵

2023-03-24 02:10 UTC, HongGuma approved these changes

2023-03-24 02:11 UTC, HongGuma commented
일단 확인했습니다~

2023-03-24 05:34 UTC, merged