feat/#17 revise packages
KDT3-final-project-team2/backend pull request #37
Opened 2023-03-26 09:25 UTC by flimberkim

## Why need this change? 
- 빠져있던 회원가입 관련 DTO 추가 및 package 수정했습니다.

## Changes ✏️
- 48551d3  jwtfilter 추가 및 패키지 수정

## Test checklist✅ (optional)
- ![image](https://user-images.githubusercontent.com/113500922/227765901-d09dab2c-33a3-46f9-910a-92be3f068b03.png)

2023-03-26 09:30 UTC, HongGuma approved these changes, later dismissed
수고하셨습니다~ 그런데 commit을 더 쪼개주세요~
jwtUtil 수정 커밋하나
dto 추가 커밋 하나 이런식으로요!

2023-03-26 09:30 UTC, HongGuma commented on build.gradle
build.gradle은 commit 로그에서 빼주세요~ 
rollback 후에 다시 push 해주세용~

2023-03-26 09:30 UTC, HongGuma commented on src/main/java/com/project/finalproject/global/jwt/utils/JwtUtil.java
> +     * 헤더로부터 LoginResDTO 생성
주석 굿~~~ 짱~~~

2023-03-26 09:47 UTC, HongGuma requested changes

2023-03-26 09:47 UTC, HongGuma commented on src/main/resources/application.properties
no~~~~~~~~~~~~~~

2023-03-26 11:25 UTC, flimberkim commented on build.gradle
넵!!

2023-03-26 11:33 UTC, flimberkim commented
pr 닫고 다시 올리겠습니다!

2023-03-26 12:00 UTC, flimberkim commented
여기서 buildgradle하고 properties 빼고 다시 reopen 하면 되나요..? 인텔리제이에서 revert 하다가 해놨던게 다 엉켜서...ㅠㅠ

2023-03-26 12:09 UTC, HongGuma commented
앗..아앗.. 파일이..

2023-03-26 12:09 UTC, HongGuma commented
내일 봐드릴게용...

2023-03-26 12:10 UTC, flimberkim commented
> 내일 봐드릴게용...

네...ㅠㅠㅠㅠ

2023-03-27 04:51 UTC, HongGuma approved these changes

2023-03-27 05:29 UTC, merged